/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/LayoutFooter.vue')['default']
    copy: typeof import('./components/ui/UiFilterMovie copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LayoutFilter: typeof import('./components/layout/LayoutFilter.vue')['default']
    LayoutFooter: typeof import('./components/layout/LayoutFooter.vue')['default']
    LayoutNavbar: typeof import('./components/layout/LayoutNavbar.vue')['default']
    MovieCard: typeof import('./components/ui/UiCardGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiCard: typeof import('./components/ui/UiCardGrid.vue')['default']
    UiCardGrid: typeof import('./components/ui/UiCardGrid.vue')['default']
    UiCardList: typeof import('./components/ui/UiCardList.vue')['default']
    UiFilter: typeof import('./components/ui/UiFilter.vue')['default']
    UiFilterFavorite: typeof import('./components/ui/UiFilterFavorite.vue')['default']
    UiFilterFavoriteMovie: typeof import('./components/ui/UiFilterFavoriteMovie.vue')['default']
    UiFilterMovie: typeof import('./components/ui/UiFilterMovie.vue')['default']
    UiNotFound: typeof import('./components/ui/UiNotFound.vue')['default']
    UiSkeletonGrid: typeof import('./components/ui/UiSkeletonGrid.vue')['default']
  }
}
